{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "marklogic.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "marklogic.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- if .Values.networkPolicy.customRules }}
    - from:
        {{- toYaml .Values.networkPolicy.customRules | nindent 8 }}
    {{- end }}
    - ports:
        {{- toYaml .Values.networkPolicy.ports | nindent 8 }}
{{- end }}