apiVersion: v1
kind: Service
metadata:
  name: {{ include "marklogic.headlessServiceName" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marklogic.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "marklogic.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports: {{- toYaml .Values.service.ports | nindent 4 }}
