{{- if .Values.imageCredentials.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haproxy.fullname" . }}
  namespace: {{ template "haproxy.namespace" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "haproxy.imagePullSecret" . }}
{{- end }}
