---
# For customization of this file please refer to eksctl config file documentation
# https://eksctl.io/usage/creating-and-managing-clusters/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: sample-name
    region: us-west-2 # Default region
    version: "1.23" # Default version

managedNodeGroups:
  - name: sample-name-ng
    instanceType: t3.large
    minSize: 2
    desiredCapacity: 4
    maxSize: 6
    volumeSize: 60
    volumeType: gp3
    updateConfig:
      maxUnavailable: 3 # or `maxUnavailablePercentage: 75` to specify maxUnavailable as a percentage of total nodes
    labels: {role: worker}
    # Note: unmanaged nodegroups (`nodeGroups` field) use a different structure (map[string]string) to express taints
    tags:
      nodegroup-role: worker
      Instance Schedule: "Yes"
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true

iam:
  withOIDC: true

addons:
- name: vpc-cni
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  version: latest  
- name: coredns
  version: latest # auto discovers the latest available
- name: kube-proxy
  version: latest

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

    # Sets the number of days to retain the logs for (see [CloudWatch docs](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html#API_PutRetentionPolicy_RequestSyntax)).
    # By default, log data is stored in CloudWatch Logs indefinitely.
    logRetentionInDays: 30