{{- if and .Values.rbac.create .Values.podSecurityPolicy.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "haproxy.fullname" . }}
  namespace: {{ template "haproxy.namespace" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "policy"
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - {{ include "haproxy.fullname" . }}
{{- end -}}
